name: Publish

# Run only after "Check" workflow has completed and only on branch master
# However, it will trigger evven if "Check" fails, therefore an if is required in jobs
on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
    branches:
      - master

jobs:
  publish:
    # Check that testing workflow has passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
