name: Publish

# Run only after "Check" workflow has completed and only on branch master
# However, it will trigger even if "Check" fails, therefore an if is required in jobs
on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
    branches:
      - master

jobs:

  changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: package.json
          token: ${{ secrets.GITHUB_TOKEN }}
          static-checking: localIsNew

  publish:
    name: Publish the package
    # Check that testing workflow has passed
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (steps.check.outputs.changed == 'true') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
