name: Send telegram message if needed

on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
    branches:
      - master
    tags:
      - '*'

jobs:
  notification:
    name: Notify about the build failure
    # Check that testing workflow has failed
    # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send warning message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}

            However, the build failed.
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
